case_sentences = ['Herein and white cat WC , the reference numerals 112 and 122 designate first and second low pass filters, respectively, the reference numeral 130 designates a signal switch, and the reference numerals TL1 and TL2 designate output transmission lines of the first and second RF amplifiers 111 and 121, respectively. BRIEF DESCRIPTION OF',
"the tool 112 and 122 designate first",
"the elements 11a-11c are for sth",
'the ignition chamber cup member <b>32</b> is made from a metal and is hard, and the protruding portions <b>454</b><i>b </i>are made from a resin and are relatively soft.',
'Shown in (C) are results for CTL generated with peptide mixture 3 (PM3), the mixture containing peptides P1, P3, P7, P9, and P11.',
'the channel electrode 110-1 included in the panel 110, and then receives an initial state identification signal from the input device 200 that is activated by the transmitted drive signal, at operations S1010 and S1015',
'selected from among a plurality of image attributes included in the image attribute change UI 810,',
'prioritized a Priority 1 (104-1 . . . 104-L)',
'Each of units 12a-12n include respective field-programmable gate arrays (FPGAs) 16a-16n, and primary input/output interfaces 18a-18n.',
'Each of units 12a-12n include respective field-programmable gate arrays (FPGAs) 16a-16n, and primary input/output interfaces 18a-18n. Each FPGA 16a-16n includes respective data bit readers 20a-20n, counters 22a-22n',
'The protrusions 331, 332, and 333 are vertically spaced apart with two different pitches p1',
'By way of example and not limitation, the opening 106 may have a width w1',
'In FIG. 6, it is seen that two flanges 54a, 54b adjacent to the groove',
'while the replaceable cutting insert 2 i',
'coupled to an output of the mixer 124, and a laser current drive 128',
'respectively the front wheels 36 and the rear wheels 42',
'As illustrated in FIG. 6, blade 34 comprises a first side 34a',
'Block 1102 acquires wireless signal strengths 510 ',
'a back plate 243 and a lens or generally transparent cover 244',
'includes a differently configured first side piece 341 and second side piece 342',
'it is determined whether a decoded version of the content is stored (2204).',
'a remote control receives a user input command (702).',
'An administrator 213 can use an administrator portal user interface 214 ',
'the assemblies 1a, 1b and 1c are',
'and each assembly bearing registrably engaging means 7',
'field oxide regions 21',
'The CPU 1 monitors an amount of image data stored in the read-in data storing area in the memory 6',
'if the card information display 7x of the manual type card vending machine 1x and the card information display 7y',
'to a second insulative plate by fastening device 52, such as a plate retaining screw.',
'The remote monitoring unit 52 transmits to the central unit 54 an initially transmitted data set, numeral 30',
'The conductors are symmetrically formed with respect to the central line X1-X1′',
'connects the third and fourth source driver ICs S3 and S4',
'the same length. The same arrangement applies to conductors for the source driver ICs S1 to Sn',
'Various user inputs and indicators are provided on the front surface 56 of the user input panel 55',
'Each of the user interface modules 50, 52 further includes a locking post 92 extending from a first end of 94',
'The top 22 preferably rotates about a hinge 24 in order to move into an opened configuration.',
'at an inter-disk information retrieval step 162.',
'the area of the bottom part 521 of the concave portion 520 is smaller than the area of the opening 523',
'It should be appreciated that the amount of projection h of the convex portion 510 in the axial direction of the spark plug 1 is 0.7 mm,',
'includes a heating process S3a and a cooling process S3b performed after the heating process S3a.',
'selected from among a plurality of image attributes included in the image attribute change UI 810,',
'located between adjacent blocks, e.g. between blocks 10.8 and 10.7',
'The secondary side 5N is likewise comprised of four rectangular coils 5NW, 5NE, 5NU and 5NL ',
'In Figure 13 there is shown a corner piece of the reservoir of Figure 11 Two external walls 102, 103 meet at this corner piece and are provided with vertical prestressing rods 108 and horizontal prestressing rods 104, Rods 104, 105 terminate in and are maintained in tension by anchoring heads 106, 107 The prestressing rods are disposed inside sheaths, the internal space being filled with concrete mortar.',
'In Figure 6 external vertical wall 35 meets roof 34 and internal vertical wall 36 These walls, 34, 35, and 36 are mutually perpendicular to one another',
'EFFE~CTS OF DIFFERENT PHOSPHATE TREATMENT! ',
'In Figure 13 there is shown a corner piece of the reservoir of Figure 11 Two external walls 102, 103 meet at this corner piece and are provided with vertical prestressing rods 108 and horizontal prestressing rods 104, Rods 104, 105 terminate in and are maintained in tension by anchoring heads 106, 107 The prestressing rods are disposed inside sheaths, the internal space being filled with concrete mortar.',
'In Figure 6 external vertical wall 35 meets roof 34 and internal vertical wall 36 These walls, 34, 35, and 36 are mutually perpendicular to one another',
'The oxide semiconductor layers <b>830</b><i>a </i>and <b>830</b><i>c </i>are',
'The secondary side 5N is likewise comprised of four rectangular coils 5NW, 5NE, 5NU and 5NL',
'according to one embodiment. In this embodiment system 10.8 includes an operating system <b>102</b> with registry <b>112</b>.',
' metal clips on the notebook 270SL align ',
'a wiring 64 for connecting to the n.sup.+ region 54 is formed.',
'formed in such a way that bottom surfaces <b>350</b>',
' in order to electrically connect the power plug terminals of the electrical apparatus and the like to the power jack terminals 11A and 12A. ',
'include power jack terminals <b>11</b>A, <b>11</b>B, <b>11</b>C, and <b>11</b>D',
'resistance to pulling forces of either of the rods <b>634</b><i>a</i>-<b>634</b><i>b </i>and compression']